#!/bin/sh /etc/rc.common

. /lib/functions/system.sh

START=19

FIRMWARE_IMAGES_DIR="/opt/intel/wave/images"
KENRELO_BJECTS_DIR="/opt/intel/lib/modules/4.9.184/net/"

start() {
    echo "INTEL WIFI START" > /dev/console
    echo "INTEL WIFI START - createConfig" > /dev/console

    # pull call data from mtd and extract it
    CAL_MTD=$(cat /proc/mtd | grep calibration | cut -d: -f1)
    gunzip /dev/${CAL_MTD} -c | gzip > /tmp/eeprom.tar.gz
    tar xvfz /tmp/eeprom.tar.gz -C /tmp
    tar xvfz /tmp/wlanconfig.gz -C /tmp
    cp /tmp/cal_wlan* /lib/firmware/

    for filename in $FIRMWARE_IMAGES_DIR/*; do
        if [ ! -L /lib/firmware/$(basename $filename) ]; then
            cp -rs $filename /lib/firmware/
        fi
    done

    for filename in $KENRELO_BJECTS_DIR/mtlk*; do
        if [ ! -L /lib/modules/$(uname -r)/$(basename $filename) ]; then
            cp -rs $filename /lib/modules/$(uname -r)/
        fi
    done

    insmod mtlkroot.ko

    # FIXME - stop mtlk from loading during module init
    #         or setup cal data before module init happens
    rmmod mtlk
    insmod mtlk.ko ap=1,1 fastpath=1,1 ahb_off=1

    if [ !  -f "/etc/config/wireless" ]; then
        /sbin/wifi config
        /usr/local/sbin/wireless_def_config
    fi

    #### HACK HACK HACK ####
    WAN_MAC=`uci get network.wan_dev.macaddr`
    if [ -z "$WAN_MAC" ]; then
        WAN_MAC="00:00:00:AD:EA:D1"
    fi

	WLAN2G_MAC=`macaddr_add $WAN_MAC 1`
    WLAN5G_MAC=`macaddr_add $WAN_MAC 2`

    uci set wireless.i2g.macaddr=$WLAN2G_MAC
    uci set wireless.i5g.macaddr=$WLAN5G_MAC
    uci commit wireless

    ifconfig wlan0 hw ether $WLAN2G_MAC
    ifconfig wlan2 hw ether $WLAN5G_MAC
}

stop() {
    echo "INTEL WIFI STOP" > /dev/console

}
